% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 02-Dec-2025 17:48:35
%
% This script assumes these variables are defined:
%
%   X - input data.
%   T - target data.

x = X';
t = T';

% Choose a Training Function
trainFcn = 'trainlm';  % Levenberg-Marquardt backpropagation.

% Create a Fitting Network
hiddenLayerSize = 6;               
net = fitnet(hiddenLayerSize,trainFcn);

% Limit number of epochs (~100 as required)
net.trainParam.epochs = 100;

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio   = 15/100;
net.divideParam.testRatio  = 15/100;

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y)     % this is overall MSE on all data

% ----- RMSE calculation over epochs -----

% MSE per epoch
mse_train = tr.perf;    % training MSE
mse_val   = tr.vperf;   % validation MSE
mse_test  = tr.tperf;   % test MSE

% Convert to RMSE
rmse_train = sqrt(mse_train);
rmse_val   = sqrt(mse_val);
rmse_test  = sqrt(mse_test);

% Epoch axis (starts at 0)
epochs = 0:numel(rmse_train)-1;

% Plot RMSE curves
figure;
plot(epochs, rmse_train, '-o'); hold on;
plot(epochs, rmse_val,   '-x');
plot(epochs, rmse_test,  '-s');
xlabel('Epoch');
ylabel('RMSE');
title('RMSE over Epochs (Train / Validation / Test)');
legend('Train','Validation','Test','Location','best');
grid on;

% View the Network
% view(net)

% Other built-in plots (optional)
% figure, plotperform(tr)
% figure, plottrainstate(tr)
% figure, ploterrhist(e)
% figure, plotregression(t,y)
% figure, plotfit(net,x,t)
